### PR TITLE
Run travis tests with tox and reveals that python3.6 is not supported yet

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by omab** [comment]
I think it's worth pointing out that the bug isn't actually in `python3-openid`, the problem is in `defusedxml` package. There was a [fix for it merged on Aug 24 2016](https://github.com/tiran/defusedxml/commit/1d342237b560e29e8401d0a22a776b52b09e0ae2), but no release so far, there's also an open [pull request](https://github.com/tiran/defusedxml/pull/4) with extra changes.

**Comment by AdamWill** [comment]
@omab the 'fix' from August does not actually fix the problem, you need my PR for defusedxml to work with 3.6.

**Comment by omab** [comment]
@AdamWill that's right, I've linked to it in my comment, I would love to see that merged and released.

**Comment by ticosax** [comment]
https://github.com/tiran/defusedxml/pull/5

**Comment by necaris** [comment]
This looks good, I'm going to go ahead and merge, and create another issue for the `defusedxml` breakage.

**Pull request merged**
